# Generated by Django 4.2.3 on 2023-08-22 02:05

from django.db import migrations, models
import django.db.models.deletion
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="news.users",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(
                related_name="news", to="news.categories"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(
                error_messages={"blank": "Este campo não pode estar vazio."}
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(validators=[news.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                error_messages={"blank": "Este campo não pode estar vazio."},
                max_length=200,
                validators=[news.validators.validate_title],
            ),
        ),
    ]
